# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type: true
        decoders:
            json: fos_rest.decoder.json
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: ~, prefer_extension: true }
services:
    fos_rest.decoder.json:
        class: FOS\RestBundle\Decoder\JsonDecoder
        public: true

