nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                bearerAuth: # arbitrary name for the security scheme
                    type: http
                    in: header
                    scheme: bearer
                    bearerFormat: JWT
        info:
            title: Przepiśnik
            description: API for Przepiśnik 2.0.0
            version: 2.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
